#!/usr/bin/env bash
# Seeds a running local API with the prototype's demo household, so the three apps can be tried
# together: Carmen's account (owner), Rosa Huamán's household, the consent and one agent installation.
# Safe to run again: existing data is reused, and every run issues a new installation credential.
#
# Usage: scripts/seed-demo.sh [agent-config-output.toml]
#   With an output path it writes a complete Te Tengo Captura configuration with the new credential.
# Requires: the API on $TT_API (default http://localhost:8080) started with `./gradlew bootRun`, jq.
set -euo pipefail
cd "$(dirname "$0")/.."

API="${TT_API:-http://localhost:8080}"
# Demo test values (local development only). Names and address come from the prototype.
CORREO="${DEMO_CORREO:-carmen@tetengo.test}"
CONTRASENA="${DEMO_CONTRASENA:-TeTengo-demo-2026}"
NOMBRE="Carmen Huamán"
ADULTO="Rosa Huamán"
DIRECCION="Jr. Los Pinos 482, San Miguel, Lima"

llamar() { # method path [json] [token]
  curl -sS -X "$1" "$API$2" -H 'Api-Version: 1' -H 'Content-Type: application/json' \
    ${4:+-H "Authorization: Bearer $4"} ${3:+--data "$3"} -w '\n%{http_code}'
}
cuerpo() { sed '$d' <<<"$1"; }
estado() { tail -n1 <<<"$1"; }

r=$(llamar POST /api/cuentas "$(jq -nc --arg c "$CORREO" --arg p "$CONTRASENA" --arg n "$NOMBRE" '{correo:$c,contrasena:$p,nombre:$n}')")
case $(estado "$r") in 201) echo "Account created: $CORREO" ;; 409) echo "Account exists: $CORREO" ;; *) cuerpo "$r"; exit 1 ;; esac

r=$(llamar POST /api/sesiones "$(jq -nc --arg c "$CORREO" --arg p "$CONTRASENA" '{correo:$c,contrasena:$p}')")
[ "$(estado "$r")" = 200 ] || { cuerpo "$r"; exit 1; }
TOKEN=$(cuerpo "$r" | jq -r .tokenAcceso); HOGAR=$(cuerpo "$r" | jq -r '.hogarId // empty')

if [ -z "$HOGAR" ]; then
  r=$(llamar POST /api/hogar "$(jq -nc --arg n "$ADULTO" --arg d "$DIRECCION" '{adultoMayor:{nombre:$n,direccion:$d,convivencia:"SOLO"}}')" "$TOKEN")
  [ "$(estado "$r")" = 201 ] || { cuerpo "$r"; exit 1; }
  TOKEN=$(cuerpo "$r" | jq -r .tokenAcceso); HOGAR=$(cuerpo "$r" | jq -r .hogarId)
  echo "Household created: $ADULTO"
fi

r=$(llamar GET /api/hogar/consentimiento "" "$TOKEN")
if [ "$(estado "$r")" != 200 ]; then
  r=$(llamar POST /api/hogar/consentimiento "$(jq -nc --arg n "$NOMBRE" '{otorgadoPor:$n,aceptadoPorAdultoMayor:true,vistaEnVivoAceptada:true}')" "$TOKEN")
  [ "$(estado "$r")" = 201 ] || { cuerpo "$r"; exit 1; }
  echo "Consent registered"
fi

# Same insert as scripts/create-installation.sh, run inside the compose PostgreSQL container.
CREDENCIAL="$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n')"
docker compose exec -T postgres psql -U tetengo -d tetengo -v ON_ERROR_STOP=1 -q \
  -v hogar="$HOGAR" -v credencial="$CREDENCIAL" <<'SQL'
insert into instalaciones (id, hogar_id, credencial_hash, creado_en, actualizado_en)
values (uuidv7(), :'hogar', encode(sha256(convert_to(:'credencial', 'UTF8')), 'hex'), now(), now());
SQL
echo "Installation created for household $HOGAR"

if [ -n "${1:-}" ]; then
  cat >"$1" <<TOML
# Generated by te-tengo-general-api/scripts/seed-demo.sh for local testing. Do not commit.
api_url = "$API"
credencial_instalacion = "$CREDENCIAL"
instalada_el = $(date +%F)

[webcam]
indice = 0
nombre = "Webcam USB HD (1080p)"
especificacion = "USB · 1920 × 1080"

[vivienda]
nombre_adulto_mayor = "$ADULTO"
direccion = "$DIRECCION"

[camara]
nombre_habitacion = "Sala"
TOML
  echo "Agent configuration written to $1"
else
  echo "Installation credential: $CREDENCIAL"
fi
echo "Sign in to the mobile app with the demo account defined at the top of this script."
